
services:
  # disable for mac users and install native with GPU
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - ai-solver
    ports:
      - "11434:11434"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    # Disable for Mac users with GPU usage
    depends_on: [ollama]
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      # - OLLAMA_BASE_URL=http://host.docker.internal:11434 # For Mac users with GPU usage
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - ai-solver
    ports:
      - "3000:8080"
    restart: unless-stopped

  ocr-mcp:
    build:
      # Contexto: Subimos a raiz (..), entramos a src, entramos a ocr-mcp
      context: ../src/ocr-mcp
      # Nos aseguramos que lea el archivo que acabamos de renombrar
      dockerfile: Dockerfile
    container_name: ocr-mcp
    volumes:
      # Mapeamos la carpeta que acabas de crear en la ra√≠z
      - ../imagenes_contenedores:/data 
    networks:
      - ai-solver
    ports:
      - "8009:8001"
    restart: unless-stopped

  ai-solver:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/ai-solver
    networks:
      ai-solver:
        aliases:
          - devcontainer
          - debug-ai-solver

  mongodb:
    image: mongo:8.0
    env_file:
      - .mongodb.env
    volumes:
      - mongodb_data:/data/db
    profiles:
      - tests
    networks:
      - ai-solver
    ports:
      - 27018:27017

volumes:
  ollama_models:
  openwebui_data:
  mongodb_data:

networks:
  ai-solver:
    name: ai-solver
    driver: bridge
